version: "3.8"
services:
  app:
    container_name: 'Next.js'
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
    volumes:
      - .:/app
    networks:
      - default
    ports:
      - "3000:3000"
